# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 11:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('driver', '0002_profile_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationDriver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_lat', models.FloatField()),
                ('home_lng', models.FloatField()),
                ('dest_lat', models.FloatField()),
                ('dest_lng', models.FloatField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='home',
        ),
    ]
